baseURL = 'https://brokenquality.com/'
locale = 'en-us'
title = 'brokenquality.com'
theme = "tella"

[markup.goldmark.renderer]
  unsafe = true

[params.logo]
main = "img/logo/bqi_logo.png"
alt = "The Broken Quality Initiative"
size = "h-15"

[[menus.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menus.main]]
name = "BQI Quiz"
pageRef = "/quiz/understanding-variation-quiz"
weight = 2

[[menus.main]]
name = "How is quality broken?"
pageRef = "/howisqualitybroken"
weight = 3

[[menus.main]]
name = "The Fix"
pageRef = "/thefix"
weight = 4

[[menus.main]]
name = "Apps"
pageRef = "/webapps"
weight = 5

[[menus.main]]
name = "Course"
url = "https://store.brokenquality.com/b/crash-course"
weight = 6

[[menus.main]]
name = "Store"
URL = "https://store.brokenquality.com/"
weight = 7

[[menus.main]]
name = "Contact"
pageRef = "/contact"
weight = 8